src/cadence/scripts/getNFTIDs.cdc
src/cadence/scripts/getNFTs.cdc
src/cadence/scripts/testGetNFTs.sh

**getNFT**
the metadata contains the next fields:
- name
- description
- author
- edition (copy number)
- link (ipfs)
**getNFTIDs**
The list of nfts, which are stored on the particular account. For any questions please contact mkalita@pixelplex.io

Scripts for xtingles (https://xtingles.com/)

---

src/cadence/scripts/getNFTIDs.cdc
src/cadence/scripts/getNFTs.cdc
src/cadence/scripts/testGetNFTs.sh

Contracts were already there, but weren't being pulled and there was no metadata.

Add Niftory contracts to Alchemy

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc

We have added both testnet and mainnet updates for our project: "Inception Animals" (https://www.inceptionanimals.com).
We've also encountered some issues both the scripts as our admin account doesn't have all the collections in the script set up, but we did test our section and it went through successfully - please feel free to let us know if you have any questions or concerns.

Add Inception Animals to Alchemy

---

src/cadence/mainnet/getNFTs.cdc
src/cadence/testnet/getNFTs.cdc

This pull request adds required fields to the Goobers NFT information.

Gooberz NFT: Add title, description and external viewer url

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc

```sh
→ flow scripts execute getNFTs.cdc --args-json '[{ "type": "Address", "value": "0x90bd6b4845e310a0" }, { "type": "Dictionary", "value": [{ "key": { "type": "String", "value": "OneFootballCollectible" }, "value": { "type": "Array", "value": [{ "type": "UInt64", "value": "90" }] } }] }]' --network mainnet
⚠️  Version warning: a new version of Flow CLI is available (v0.30.2).
Read the installation guide for upgrade instructions: https://docs.onflow.org/flow-cli/install
Result: [s.0fce97e69ff4ff364c102076a4fa77fcd12737998f419f73e61f820739d5c89e.NFTData(
contract: s.0fce97e69ff4ff364c102076a4fa77fcd12737998f419f73e61f820739d5c89e.NFTContract(
name: "OneFootballCollectible", 
address: 0x6831760534292098, 
storage_path: "OneFootballCollectible.CollectionStoragePath", 
public_path: …
```

Add OneFootballCollectible

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc

This PR adds support for FlowFans NFT (Flow Chinese community)
https://github.com/FlowFans/FlowChinaBadge
This NFT is generated by `freshmint` using `token_uri` to fetch metadata from ipfs
Tested with the flow scripts provided as well as the `testGetNFTs.sh` script
---
BTW, I copied the `testGetNFTs.sh` to testnet folder and modified it to support testnet, and i found some issues in the scripts. I just commented those issue codes and tested my part...

Add FlowFans contract

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh

We are KLKTN and we have a second contract `KlktnNFT2` to add to Alchemy API. Some testing scripts on mainnet are listed below:
`flow scripts execute getNFTIDs.cdc 0x3564d691f3ae6103 --network mainnet`:
```
Result: {"CricketMoments": [4548], "Crave": [], "TopShot": [], "FantastecNFT": [2358], "Vouchers": [], "TuneGO": [], "TheFabricantMysteryBox_FF1": [], "Xtingles_NFT": [], "KlktnNFT": [6010, 6006, 6011, 6009, 6008, 6007], "RareRooms_NFT": [], "StarlyCard": [], "MusicBlock": [], "Everbloom": [], "NyatheesOVO": [70], "SportsIconCollectible": [], "KlktnNFT2": [8, 2, 27], "Gaia": [], "ThingFund": [], "RCRDSHPNFT": [], "Beam": [], "MatrixWorldFlowFestNFT": [], "KOTD": [], "BlockleteGames_NFT": [], "RaceDay_NFT": [57689], "EternalShard": [1379], "InceptionAnimals": [103], "Mynft": [], "CNN": …
```

Add KlktnNFT2 scripts

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh

Adding Costacos, CanesVault, AmericanAirlines, TheNextCartel, AthletesUnlimited, Art, DGD.  Updating fields for CNN, Andbox, RaceDayNFT, RareRooms.

Adding GigLabs mainline contracts; some updates to existing ones

---

src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Added a pull request for testnet integration of Alchemy.
Added a method in getNFTIDs and getNFTs file and added testcases in testnet folder too.
We have created a new Marketplace on flow. Please review our repo so we can integrate our mainnet later and fulfill all the blocto requirements.

Nft contract/testnet

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Add Gogoro and Yahoo NFTs

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

- Added NowggNFT contract
- Added testcases for mainnet
- Added testcases for testnet

NowggNFT contract details

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Add RacingTime NFTs

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Add MatrixWorldAssetsNFT support

feat(feat): Add MatrixWorldAssetsNFT support

---

src/cadence/mainnet/getNFTs.cdc
src/cadence/testnet/getNFTs.cdc

Some contracts need to be updated to include metadata in the new format. Tagging the owners here:
1. NowggNFT @sudhanshu-bst

Change Metadata type to {String:String?}

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Please note that the mainnet tests do not work atm since there have not been any token minted yet.
Testnet tests work correctly.

Feat: Add DropzToken support

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Added support for Necryptolis NFTs.

Add Necryptolis.

---

src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc

We are removing the broken contracts

Fix testnet tests due to missing Crave contract and contract redeployment 

---

src/cadence/mainnet/getNFTs.cdc
src/cadence/testnet/getNFTs.cdc

Would like to add one more metadata 'rarity' for the NFTData object

Add metadata to ARTIFACT and ARTIFACTPack

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

added Swaychain to alchemy

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

-add TheFabricantS2ItemNFT NFT contract from The Fabricant

add TheFabricantS2ItemNFT contract

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Adding `metadata` support for the smart contract

Add metadata support to Ozone Metaverse 

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Add Blindbox voucher (NFT NYC event)

Add Blindbox voucher (NFT NYC event)

---

src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTs.cdc

BTW you have a lot of contracts that did not upgrade to SecureCadence

Adding support for Starly metadata

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh
src/cadence/testnet/getNFTIDs.cdc
src/cadence/testnet/getNFTs.cdc
src/cadence/testnet/testGetNFTIDs.sh
src/cadence/testnet/testGetNFTs.sh

Add ByteNextMedalNFT collection

Add ByteNextMedalNFT collection

---

src/cadence/mainnet/getNFTIDs.cdc
src/cadence/mainnet/getNFTs.cdc
src/cadence/mainnet/testGetNFTIDs.sh
src/cadence/mainnet/testGetNFTs.sh

I deleted the old pull request and created a new pull request to add LibraryPass. Can you please review and merge it asap before other pull requests are added so that there's no merge conflics?

feat - add LibraryPass
